defaults: &defaults
  iterations: 4200

stages:
  - name: "1 robot"
    <<: *defaults
    environment:
      n_robots_blue: 1
      n_robots_yellow: 0

  - name: "2 robots"
    environment:
      n_robots_blue: 2
      n_robots_yellow: 0
    <<: *defaults

  - name: "2 vs 2 static"
    <<: *defaults
    environment:
      n_robots_blue: 2
      n_robots_yellow: 2

