[project]
name = "dll-project-soccer"
version = "0.1.0"
description = "Transformer-based RL policies for cooperative soccer"
authors = [{ name = "abc", email = "111@222.333" }]
requires-python = "==3.10.*"
dependencies = [
    "rc-robosim>=1.2",
    "rsoccer-gym",
    "gymnasium>=0.29.1",
    "pygame>=2.1",
    "setuptools<81",
    "torch==2.4.1",
    "numpy",
    "tensorboard>=2.10.0",
    "wandb>=0.13.11",
    "moviepy>=1.0.3",
    "huggingface-hub>=0.11.1",
    "rich<12.0",
    "tenacity>=8.2.2",
    "tyro>=0.5.10",
    "pyyaml>=6.0.3",
    "pydantic>=2.13.4",
]

[tool.uv.sources]
rsoccer-gym = { git = "https://github.com/robocin/rSoccer.git" }

[dependency-groups]
dev = [
    "basedpyright>=1.39.9",
    "matplotlib>=3.10.9",
    "ruff>=0.15.20",
]
