""" This file was generated by claude sonnet online chat.

Run a saved agent checkpoint in the environment, without training.

Usage:
    python simulate.py --model-path runs/.../my_exp_stage0_explore.cleanrl_model \
                        --config config.yml --stage-name explore --episodes 10

    # with a live rendered window:
    python simulate.py --model-path ... --config config.yml --stage-name explore \
                        --episodes 5 --render

    # with rendering / video capture instead:
    python simulate.py --model-path ... --config config.yml --stage-name explore \
                        --episodes 5 --capture-video --video-dir videos/eval_run
"""
import os
import time
from dataclasses import dataclass
from typing import Optional

import numpy as np
import torch
import tyro
import gymnasium as gym

import rsoccer_gym  # noqa: F401
import myenvs  # noqa: F401

from agent import Agent
from config import load_config
from ppo import make_env  # reuse the exact same env-building logic as training


@dataclass
class SimArgs:
    model_path: str
    """path to the .cleanrl_model checkpoint to load"""
    config: str = "config.yml"
    """path to the yaml config used during training (for env args + architecture hyperparams)"""
    stage_name: Optional[str] = None
    """which stage's environment config to simulate in (defaults to the first stage)"""
    episodes: int = 10
    """number of episodes to run"""
    deterministic: bool = True
    """use the policy mean instead of sampling (recommended for evaluation)"""
    render: bool = False
    """open a live window and render each step as it happens"""
    fps: int = 30
    """playback speed cap when --render is set (steps per second)"""
    capture_video: bool = False
    """record video of the episodes instead of/as well as live rendering"""
    video_dir: str = "videos/eval"
    """directory to save videos to, if capture_video is set"""
    cuda: bool = True
    """use GPU if available"""
    seed: int = 1
    """environment seed"""


def build_render_env_fn(env_id: str, gamma: float, flatten: bool, environment_args: dict):
    """Single env with a live 'human' window instead of rgb_array/video capture.
    Mirrors train.make_env's wrapper stack, minus RecordVideo (incompatible
    with render_mode='human' — SDL owns the window directly in that mode)."""
    def thunk():
        env = gym.make(env_id, render_mode="human", **(environment_args or {}))
        if flatten:
            env = gym.wrappers.FlattenObservation(env)
        env = gym.wrappers.RecordEpisodeStatistics(env)
        env = gym.wrappers.ClipAction(env)
        env = gym.wrappers.NormalizeReward(env, gamma=gamma)
        env = gym.wrappers.TransformReward(env, lambda reward: np.clip(reward, -10, 10))  # pyright: ignore[reportArgumentType, reportCallIssue]
        return env
    return thunk


def main():
    args = tyro.cli(SimArgs)
    config = load_config(args.config)

    if args.render and args.capture_video:
        raise ValueError("--render and --capture-video are mutually exclusive "
                          "(render_mode='human' vs 'rgb_array' can't both drive the same env)")

    # pick the stage whose environment settings (n_robots_blue/yellow etc.)
    # we want to simulate in
    if args.stage_name is not None:
        stage = next((s for s in config.stages if s.name == args.stage_name), None)
        if stage is None:
            raise ValueError(f"no stage named '{args.stage_name}' in {args.config}")
    else:
        stage = config.stages[0]
    env_args = stage.environment.model_dump()

    device = torch.device("cuda" if args.cuda and torch.cuda.is_available() else "cpu")

    # single env, no vectorization needed for a simulation/eval run
    if args.render:
        env_fn = build_render_env_fn(
            config.env_id, gamma=config.gamma,
            flatten=config.agent_type == "mlp", environment_args=env_args,
        )
    else:
        env_fn = make_env(
            config.env_id, idx=0, capture_video=args.capture_video,
            run_name=os.path.basename(args.video_dir), gamma=config.gamma,
            flatten=config.agent_type == "mlp", environment_args=env_args,
        )
    env = gym.vector.SyncVectorEnv([env_fn])  # Agent expects a vectorized env interface

    agent = Agent(
        env, config.rpo_alpha, agent_type=config.agent_type, d_model=config.d_model,
        n_layers=config.n_layers, n_heads=config.n_heads, ff_dim=config.ff_dim,
        dropout=config.dropout, critic_pooling=config.critic_pooling,
    ).to(device)
    agent.load_state_dict(torch.load(args.model_path, map_location=device))
    agent.eval()  # disable dropout etc. — important even though dropout=0.0 by default
    agent.set_env(env)

# opponent agent — same story, needs env too, and env needed a placeholder
# opponent policy already in place before this point (built during gym.make)
    if stage.environment.opponent_strategy == "Agent" and stage.environment.opponent_model:
        opponent_agent = Agent(
            env, config.rpo_alpha, agent_type=config.agent_type, d_model=config.d_model,
            n_layers=config.n_layers, n_heads=config.n_heads, ff_dim=config.ff_dim,
            dropout=config.dropout, critic_pooling=config.critic_pooling).to(device)
        opponent_agent.load_state_dict(torch.load(stage.environment.opponent_model, map_location=device))
        opponent_agent.eval()
        env.call("set_opponent_agent", opponent_agent)

    returns = []
    obs, _ = env.reset(seed=args.seed)
    obs = torch.Tensor(obs).to(device)
    frame_interval = 1.0 / args.fps if args.render and args.fps > 0 else 0.0

    for ep in range(args.episodes):
        ep_return = 0.0
        done = False
        while not done:
            step_start = time.time()

            with torch.no_grad():
                # NOTE: check your Agent's actual signature — if
                # get_action_and_value doesn't support a `deterministic` /
                # `action=None` mode that returns the policy mean instead of
                # a sample, either add that option to Agent, or fall back to
                # stochastic sampling (still informative, just noisier).
                if args.deterministic and hasattr(agent, "get_action_and_value"):
                    try:
                        action, _, _, _ = agent.get_action_and_value(obs, deterministic=True)
                    except TypeError:
                        # Agent doesn't support a deterministic flag — fall back
                        action, _, _, _ = agent.get_action_and_value(obs)
                else:
                    action, _, _, _ = agent.get_action_and_value(obs)

            obs, reward, terminations, truncations, infos = env.step(action.cpu().numpy())
            obs = torch.Tensor(obs).to(device)
            ep_return += reward[0]
            done = bool(terminations[0] or truncations[0])

            if args.render:
                env.call("render")  # SyncVectorEnv: dispatch render() to the underlying env
                elapsed = time.time() - step_start
                if frame_interval > elapsed:
                    time.sleep(frame_interval - elapsed)

        returns.append(ep_return)
        print(f"episode {ep + 1}/{args.episodes}: return={ep_return:.2f}")

    print(f"\nmean return over {args.episodes} episodes: "
          f"{np.mean(returns):.2f} ± {np.std(returns):.2f}")

    env.close()


if __name__ == "__main__":
    main()
